version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    expose:
     - "2181"
  kafka:
    image: wurstmeister/kafka
    expose:
     - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "input:1:1,output1:1:1,output2:1:1"
      KAFKA_LOG_RETENTION_HOURS: 1
  kafka-streams-app:
    image: kafkastreams-app:latest
    depends_on:
      - "kafka"